### ISSUE TITLE
DeepLC 0.1.14 crashes my computer systematically when a peptide file for calibration is not supplied

### ISSUE THREAD

**Issue by MarcIsak** [compomics/DeepLC#11]
Hi, 

I have used the DeepLC v. 0.1.14 python module many times in Ubuntu 18.04, and managed to run iRT predictions successfully every time.  However, when trying to run DeepLC without supplying a peptide file for calibration, my computer crashes when running a task. I have so far predicted iRTs for 1.6 million peptide sequences.

My inital guess was that I had to set --batch_num to a lower value to lower the memory footprint. So I tried to set it to 100 000 and even 75 000, and tried to use less threads like 4 or even 2 (I use an Intel(R) Core(TM) i9-7900X CPU @ 3.30GHz). I only have 32 GB RAM though, but since I dropped the --batch_num to 75 000 with --n_threads 2, I think that it should work. But the computer crashes still. 

Any ideas on this? 

Best,

Marc

**Comment by RobbinBouwmeester** [comment]
Hi Marc,

Are there any specific errors you get or does the GUI just freeze?

Maybe it would be easier to diagnose if you share the input files (probably most practical via mail).

Hope we can fix your problem.

**Comment by RobbinBouwmeester** [comment]
Hi Marc, just to check, did you try the latest version (0.1.16)? Maybe this resolves your calibration issues.
