### ISSUE TITLE
Possibility to retrain a model

### ISSUE THREAD

**Issue by cctsou** [compomics/DeepLC#12]
Is it possible to retrain a new model? or once it's calibrated could we save the calibrated models for future use?

**Comment by RobbinBouwmeester** [comment]
Dear Chih-Chiang Tsou, yes it is possible to train new models. The python scripts to retrain are available in "figures_without_models.zip" here: https://doi.org/10.5281/zenodo.3706875

In that zip file you can use "run_full_mod.py" to retrain. It should be documented, but if things are unclear please do not hesitate to ask.
