### ISSUE TITLE
DeepLC as a docker image

### ISSUE THREAD

**Issue by MarcIsak** [compomics/DeepLC#16]
Hi, 

I just wonder if there's a plan to distribute a  Docker image of DeepLC later? Btw, I think this tool is
performing really well given the benchmarks that I have done between predicted vs. experimental RT and iRTs. 

Best,

Marc

**Comment by RalfG** [comment]
Hi Marc, Glad DeepLC is working well for you! As DeepLC is in bioconda, there's already a Docker image available:
https://quay.io/repository/biocontainers/deeplc

**Comment by MarcIsak** [comment]
Hi Ralf, 

my bad! Initially I did not manage to pull the image as I did not provide any tag ( default tag: latest, did not work). But I found one of the valid tags and managed to pull the image. The application works nicely so thank you!

Marc
