### ISSUE TITLE
DeepLC (tensorflow) does not seem to obey num_jobs 

### ISSUE THREAD

**Issue by RalfG** [compomics/DeepLC#19]
DeepLC (tensorflow) does not seem to obey num_jobs, as NUMEXPR_MAX_THREADS env variable is not set. 

```
2021-02-05 08:57:40 // INFO // numexpr.utils // Note: NumExpr detected 32 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2021-02-05 08:57:40 // INFO // numexpr.utils // NumExpr defaulting to 8 threads.
```

I would propose to first check if `NUMEXPR_MAX_THREADS` has already been set, and if not, we can set it to the `num_jobs` parameter that was passed to DeepLC.

**Comment by RobbinBouwmeester** [comment]
Dislike doing this... Still did set the NUMEXPR_MAX_THREADS. Should not be done system-wide. The way it is added now **will** cause bugs/problems in the future.

#DeepLC@a69e996

**Comment by RalfG** [comment]
Strange that it did not work in my case... I'd have to look into what happened.

What do you mean, system-wide? Changes with `os.environ()` only affect the current process and child-processes (e.g. `os.system()`), see https://docs.python.org/3/library/os.html#os.putenv.
