### ISSUE TITLE
What is the unit of tr: retention time (only required for calibration)?

### ISSUE THREAD

**Issue by chinmayaNK22** [compomics/DeepLC#21]
Hi,

I would like to know the unit used for the retention time for prediction?

**Comment by RobbinBouwmeester** [comment]
Without calibration there is essentially no unit. The retention times for training are divided by the maximum observed retention time and multiplied by a factor of 10.

With calibration the predicted retention time should take the same units as the peptides used for calibration.

For more details see: https://www.biorxiv.org/content/10.1101/2020.03.28.013003v2

**Comment by RobbinBouwmeester** [comment]
I will close this issue now, if you have more questions regarding this issue please reopen.
