### ISSUE TITLE
Deeplc docker GPU support

### ISSUE THREAD

**Issue by Hendricks27** [compomics/DeepLC#36]
Hi,

Thank you for providing such useful tools! Good job!
Something related to https://github.com/compomics/DeepLC/issues/16
Does the docker version support GPU? In specific Tesla A100/V100 series GPUs.
Thanks.

Best,
Wenjin

**Comment by RobbinBouwmeester** [comment]
Dear Wenjin,

For now the GPU is supported through changing the following:
```

Q: I have a graphics card, but DeepLC is not using the GPU. Why?

For now DeepLC defaults to the CPU instead of the GPU. Clearly, because you want to use the GPU, you are a power user :-). If you want to make the most of that expensive GPU, you need to change or remove the following line (at the top) in deeplc.py:

# Set to force CPU calculations
os.environ['CUDA_VISIBLE_DEVICES'] = '-1'

Also change the same line in the function reset_keras():

# Set to force CPU calculations
os.environ['CUDA_VISIBLE_DEVICES'] = '-1'

Either remove the line or change to (where the number indicates the number of GPUs):

# Set to force CPU calculations
os.environ['CUDA_VISIBLE_DEVICES'] = '1'
```
Our experience is that prediction through CPU and possibly using the library feature are sufficiently fast for most tasks. However, if you really need the computational power of the GPU I am willing to help you set that up. Feel free to contact me at: robbin.bouwmeester@ugent.be

Kind regards,

Robbin

**Comment by Hendricks27** [comment]
Hi Robbin,

Thank you so much for the detailed reply. I am closing the issue now.

Best,
Wenjin
