### ISSUE TITLE
scikit-learn / sklearn missing from dependency list 

### ISSUE THREAD

**Issue by RalfG** [compomics/DeepLC#37]
sklearn is missing as a dependency in setup.py and the conda yaml file:
https://github.com/bioconda/bioconda-recipes/blob/master/recipes/deeplc/meta.yaml

The GitHub Actions tests pass, as sklearn was already a test dependency. The bioconda tests fail, however: 
https://github.com/bioconda/bioconda-recipes/pull/32320

The sklearn dependency seems to have been added in https://github.com/compomics/DeepLC/commit/675f5ab676e33ed4f7eee9824a830417f647664e

**Comment by RobbinBouwmeester** [comment]
@paretje Indeed, making this import optional is probably best. With latest merged PR [675f5ab](https://github.com/compomics/DeepLC/commit/675f5ab676e33ed4f7eee9824a830417f647664e) is this fixed?

**Comment by RalfG** [comment]
Fixed in #38
