### ISSUE TITLE
pip install on Python 3.10 not working correctly

### ISSUE THREAD

**Issue by levitsky** [compomics/DeepLC#39]
Hi and thank you for the great package!

`pip install deeplc` behaves strangely on Python 3.10. It downloads mutltiple versions of deeplc:

```
pip install deeplc
Collecting deeplc
  Downloading deeplc-0.2.0-py3-none-any.whl (77.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.8/77.8 MB 2.1 MB/s eta 0:00:00
Requirement already satisfied: numpy<2,>=1.17 in /home/lev/venv/ms1/lib/python3.10/site-packages (from deeplc) (1.22.1)
Requirement already satisfied: setuptools>=42.0.1 in /home/lev/venv/ms1/lib/python3.10/site-packages (from deeplc) (59.6.0)
  Downloading deeplc-0.1.39-py3-none-any.whl (77.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.8/77.8 MB 1.3 MB/s eta 0:00:00
  Downloading deeplc-0.1.37-py3-none-any.whl (77.8 MB)
     ━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.8/77.8 MB 1.0 MB/s eta 0:00:51
... etc.
```
Any idea what the reason and the solution may be?

**Comment by RobbinBouwmeester** [comment]
Dear levitsky,

I have not seen that behavior before, will look into it and get back at you.

Kind regards,

Robbin

**Comment by levitsky** [comment]
Some context that might help: I also tried installing from Github like this:

```
pip install git+https://github.com/compomics/DeepLC
Collecting git+https://github.com/compomics/DeepLC
  Cloning https://github.com/compomics/DeepLC to /tmp/pip-req-build-4ekkzm3h
  Running command git clone --filter=blob:none --quiet https://github.com/compomics/DeepLC /tmp/pip-req-build-4ekkzm3h
  Resolved https://github.com/compomics/DeepLC to commit 2ed9de91f29a8a82eb7982f9a64d6dd1120a46eb
  Preparing metadata (setup.py) ... done
Requirement already satisfied: setuptools>=42.0.1 in ./venv/ms1/lib/python3.10/site-packages (from deeplc==0.2.0) (59.6.0)
ERROR: Could not find a version that satisfies the requirement tensorflow<3,>=2.2 (from deeplc) (from versions: 2.8.0rc0, 2.8.0rc1)
ERROR: No matching distribution found for tensorflow<3,>=2.2
```
However, directly running `pip install tensorflow` works and installs 2.8.0rc1.
After that, I am able to install `deeplc`.

**Comment by RalfG** [comment]
Regarding the AVX issue, it seems that your CPU is not supported by the tensorflow binaries installed from pip. You can try to build from source, or maybe conda?

**Comment by levitsky** [comment]
I will update this comment with more specific info, but it was several recent versions of pip on Linux in a clean virtualenv (not Conda).

**Comment by levitsky** [comment]
I am currently unable to reproduce my own report. `pip install deeplc` works fine. I noticed that it now installs Tensorflow 2.8.0, which was released today. I wonder if the problem was related to the fact that only a release candidate version was available before, and if it is in fact the reason, which package is responsible for this quirk.

**Comment by RalfG** [comment]
Very strange... DeepLC is pretty liberal with the tensorflow requirement, accepting anything between >=2.2 and <3.

**Comment by RobbinBouwmeester** [comment]
Great that is now working! Although I would like to know what caused the quirk... For now I will close this issue. Thank you again for the report!

**Comment by levitsky** [comment]
For extra information: a similar situation now occurs on Python 3.12, which is not supported by Tensorflow in official releases (2.15.0), but a direct `pip install tensorflow` command installs `2.16.0rc0`. After that, `pip install deeplc` installs an old version `2.2.5` instead of the latest version `2.2.27`.
