### ISSUE TITLE
Low prediction accuracy for versions 2.0.4+

### ISSUE THREAD

**Issue by markmipt** [compomics/DeepLC#54]
Hi,

I've noticed that starting from version 2.0.4 update I get much worse RT prediction accuracy compared to version 1.1.2.
I have a set of peptides (~2000) which is split into two parts - one for DeepLC calibration and one for estimation of predicted RTs. 
The old version provides me with **0.124** min standard deviation for the difference between predicted and experimental RTs, while the new one (2.0.4) - **0.321** min. 

All peptides have no modifications except fixed Carbamidomethyl of C.
I run DeepLC with basic command line options (deeplc_path, '--file_pred', estimate_file_name, '--file_cal', calibrate_file_name, '--file_pred_out', out_file_name).
The only strange thing in my data is ~5-20% peptide FDR.

The same behavior I see for another dataset, as well as for the latest DeepLC version (2.1.9).

Please find the attached DeepLC logs, files for testing and the figures with results.

Regards,
Mark
![deeplc_bug_hist](https://github.com/compomics/DeepLC/assets/12832559/4ef0228f-b860-4954-95f6-a798df8f4041)
![deeplc_bug_scatterplot](https://github.com/compomics/DeepLC/assets/12832559/3bec3171-bf71-48d5-90a1-06defe454927)

[test_calibrate.txt](https://github.com/compomics/DeepLC/files/11665018/test_calibrate.txt)
[test_estimate.txt](https://github.com/compomics/DeepLC/files/11665019/test_estimate.txt)

[Log_DeepLC112.txt](https://github.com/compomics/DeepLC/files/11665026/Log_DeepLC112.txt)

[Log_DeepLC204.txt](https://github.com/compomics/DeepLC/files/11665025/Log_DeepLC204.txt)

**Comment by RobbinBouwmeester** [comment]
Hi @markmipt,

Thank you for spotting this bug! 

Last week I was also contacted by someone else that the feature calculation between these versions is different (i.e., the calculated compositions are not the same).

This difference in calculated features is also the cause of lower performance. I will need to retrain models with the new features to account for this. I will do the retraining ASAP.

Kind regards,

Robbin

**Comment by RobbinBouwmeester** [comment]
The v2.2.0 release should fix this issue @7aa082d

**Comment by markmipt** [comment]
Thanks!

Now the results looks similar.

![deeplc_bug_scatterplot2](https://github.com/compomics/DeepLC/assets/12832559/327301fb-d7d8-4028-ba33-3bd7ec5c23d3)
![deeplc_bug_hist2](https://github.com/compomics/DeepLC/assets/12832559/1396d62c-f5bd-48ae-9b18-6d81354e71f0)


Regards,
Mark
