### ISSUE TITLE
deeplc gui

### ISSUE THREAD

**Issue by HR-RH** [compomics/DeepLC#57]
Hello，When using version 2.2.3 of deeplc gui, the following problems occurred:

Traceback (most recent call last):
  File "deeplc\gui.py", line 38, in <module>
    start_gui()
  File "gooey\python_bindings\gooey_decorator.py", line 134, in <lambda>
    return lambda *args, **kwargs: func(*args, **kwargs)
  File "deeplc\gui.py", line 35, in start_gui
    main(gui=True)
  File "deeplc\__main__.py", line 70, in main
    run(**vars(argu))
  File "deeplc\__main__.py", line 181, in run
    if len(psm_list_cal) > 0:
UnboundLocalError: local variable 'psm_list_cal' referenced before assignment

And the input file I used is examples/datasets/seqs_exp.csv of the deeplc source code.

**Comment by RobbinBouwmeester** [comment]
Dear HR-RH,

This should be fixed in version 2.2.4 of the GUI. Could you let me know if it now works?

Thank you!

Robbin

**Comment by HR-RH** [comment]
Thank you for your answer. I will try again. But now I have one more question. If I want to use your source code to retrain a data set, is it ok? If so, what should I do?

**Comment by RobbinBouwmeester** [comment]
Hi,

It is actually best if you use [https://github.com/RobbinBouwmeester/DeepLCRetrainer](url) for that, but this option is not yet available in the GUI.

If you are willing to do some coding I can help you in using deeplcretrainer, also see: [https://proteomicsml.org/tutorials/retentiontime/deeplc-transfer-learning.html](url)

**Comment by RobbinBouwmeester** [comment]
I will close this issue for now, you can reopen it if you need further help.
