### ISSUE TITLE
batch_num is not used anymore in the resent versions

### ISSUE THREAD

**Issue by markmipt** [compomics/DeepLC#58]
Hi again,

I've noticed that latest versions of DeepLC (2+) does not use argument batch_num anymore (Or did I read the code wrong?). That leads to GPU memory errors when DeepLC is used to predict RTs for few millions of peptides on the weak GPU.

I compare everything to version 1.1.2, which is the most stable and effective for me right now. And works fine for the same set of peptides on the same hardware.

Regards,
Mark

**Comment by RobbinBouwmeester** [comment]
Hi Mark,

I will have a look! And yes, it is also our experience the 2+ version can sometimes still be problematic. Still ironing out some of the issue...

Kind regards,

Robbin

**Comment by RobbinBouwmeester** [comment]
You should be able to use batches again, (>= v2.2.7, aece880). Also maybe have a look at batch_num_tf when you initialize DeepLC, that determines the internal batch size of tensorflow. Batch_num parameter has (again) the same behavior as before.

**Comment by markmipt** [comment]
Hi Robbin,

Thanks for the commit. However, it was not enough to fix memory errors. But I've finally found the problem and made an extra patch, see pull request for details.

Regards,
Mark
