### ISSUE TITLE
Training new models

### ISSUE THREAD

**Issue by KarlClauser** [compomics/DeepLC#63]
Issue #12 from May 2020 response was:
>>yes it is possible to train new models. The python scripts to retrain are available in "figures_without_models.zip" here: >>https://doi.org/10.5281/zenodo.3706875
>>In that zip file you can use "run_full_mod.py" to retrain. It should be documented, but if things are unclear please do not hesitate to ask.

I downloaded that zip and can not find  "run_full_mod.py" perhaps you mean "run.py"?

Is there a more current version of the new model training capability?
The current release contains a file called deeplc/trainl3.py

**Comment by RobbinBouwmeester** [comment]
Dear Karl,

It should be in the zip file, going to check now. There are multiple zip files, which one did you check?

About training your own models, you can now also have a look at this tutorial that uses a new package (retrainer) to apply either transfer learning or train new models from scratch:

[https://proteomicsml.org/tutorials/retentiontime/deeplc-transfer-learning.html](https://proteomicsml.org/tutorials/retentiontime/deeplc-transfer-learning.html)

Also looking into the other issue you posted will come back to that soon.

Kind regards,

Robbin

**Comment by KarlClauser** [comment]
Hi Robbin,

I checked the one indicated: figures_without_models.zip
proteomicsml.org looks to be a great resource, I will work from that instead.
