### ISSUE TITLE
How is it possible to predict RT when DeepLC doesnt know the LC gradient

### ISSUE THREAD

**Issue by candidaorelmex** [compomics/DeepLC#66]
Hi,

DeepLC enjoys a good reputation which is why I'd like to use it to predict retention times of peptides with with a specific gradient. Unfortunately I cannot provide calibration peptides with that gradient.

When I feed the DeepLC streamlit GUI my peptides to predict it returns a table with valuesin the "predicted_tr" column between 1 and 10. 

1. how do I interpret this value?
2. how can DeepLC predict the retention time without knowing anything about the LC gradient I am using? (with he simple scenario that my peptides elute somewhere between 0% and 100% ACN)

Thank you for your help!

**Comment by RobbinBouwmeester** [comment]
FYI, most of the times calibration peptides are chosen from the most confident identifications. So you can use the peptides you are already very certain of their identification, to evaluate less confident identifications.

**Comment by RobbinBouwmeester** [comment]
I will close this issue for now, but feel free to re-open it if you need any further help.

**Comment by candidaorelmex** [comment]
Dear Robbin, thanks a lot for your elaobarate answer.

We want to compare weather the it makes a big difference to us if we use calibration peptides (defined from some other run that ran on the column) vs just using the uncalibrated DeepLC output. We then saw that the uncalibrated output is hard to interpret without more details.

What was the %B used for the runs used for the development of the prediction model=

Do you have a couple of examples how to interpret the values? E.g., peptide X has tr = 5.5 in the unpredicted model, corresponding to Y %ACN in the chormatography gradient?

Thanks for your help!

Best,
Ilja
