### ISSUE TITLE
Documentation: table of peptide properties of training data sets

### ISSUE THREAD

**Issue by vrkosk** [compomics/DeepLC#73]
Could you add a table to the documentation that better summarises the available models? Something analogous to the MS2PIP model table: [https://github.com/compomics/ms2pip?tab=readme-ov-file#specialized-prediction-models](https://github.com/compomics/ms2pip?tab=readme-ov-file#specialized-prediction-models)

For example, I can try to find out what `full_hc_PXD008783_median_calibrate` is based on by looking at the data set info in PRIDE, but I don't know what median calibrate means. Or in `full_hc_Xbridge_fixed_mods`, what fixed mods is it referring to and does Xbridge mean disulfide bridge or something else? What I'd most like to know is enzyme, species and type of LC.

**Comment by RobbinBouwmeester** [comment]
Hey, yes sure. I should update these anyway, since a lot has changed lately. I will set a reminder mid-june.

**Comment by RobbinBouwmeester** [comment]
Should be fixed in [https://github.com/compomics/DeepLC/commit/eb9aa60c3d666ba277f6da8669a85f8fa0f871b4](https://github.com/compomics/DeepLC/commit/eb9aa60c3d666ba277f6da8669a85f8fa0f871b4)
