### ISSUE TITLE
Python 3.8 compatibility

### ISSUE THREAD

**Issue by paretje** [compomics/DeepLC#9]
Currently, DeepLC is marked as incompatible with python 3.8. It might be interesting to resolve any incompatibilities and remove the restriction.

**Comment by RalfG** [comment]
Yup, I agree. @RobbinBouwmeester, do you remember why Python 3.8 doesn't work?

**Comment by RalfG** [comment]
Was it because we use Tensorflow 1, which [does not support Python 3.8](https://github.com/tensorflow/tensorflow/issues/33374)?

**Comment by RobbinBouwmeester** [comment]
From what I remember DeepLC was not tested on 3.8; lets give it a try.
